# Generated by Django 3.2.6 on 2023-07-29 02:44

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Commande',
            fields=[
                ('idcom', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateTimeField(default=datetime.datetime.now)),
                ('etat', models.IntegerField(default=0)),
                ('total', models.DecimalField(decimal_places=5, max_digits=100, null=True)),
                ('vandor', models.CharField(default='v9096', max_length=200)),
                ('idclt', models.IntegerField()),
                ('idpro', models.IntegerField()),
                ('action', models.CharField(default='direct', max_length=100)),
            ],
            options={
                'db_table': 'orbitcommande',
            },
        ),
        migrations.CreateModel(
            name='Compte',
            fields=[
                ('idpcompt', models.AutoField(primary_key=True, serialize=False)),
                ('montant', models.DecimalField(decimal_places=2, default=0.0, max_digits=100)),
                ('idclt', models.IntegerField()),
                ('etat', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'orbitcompte',
            },
        ),
        migrations.CreateModel(
            name='DmdCredit',
            fields=[
                ('iddmd', models.AutoField(primary_key=True, serialize=False)),
                ('idclt', models.IntegerField(default=1)),
                ('nomclt', models.CharField(max_length=255, null=True)),
                ('noment', models.CharField(max_length=255, null=True)),
                ('status', models.IntegerField(default=0)),
                ('idpro', models.IntegerField()),
            ],
            options={
                'db_table': 'orbitdmdcredit',
            },
        ),
        migrations.CreateModel(
            name='Entreprise',
            fields=[
                ('ident', models.AutoField(primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=255)),
                ('mdpent', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'orbitentreprise',
            },
        ),
        migrations.CreateModel(
            name='Precommande',
            fields=[
                ('idprecom', models.AutoField(primary_key=True, serialize=False)),
                ('idpro', models.IntegerField()),
                ('idclt', models.IntegerField()),
                ('date', models.DateTimeField(default=datetime.datetime.now)),
                ('nbrjour', models.IntegerField(default=30)),
                ('etat', models.IntegerField(default=0)),
                ('prix', models.DecimalField(decimal_places=2, default=10.2, max_digits=10)),
                ('description', models.TextField(default='description du  produit')),
            ],
            options={
                'db_table': 'orbitprecommande',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('idpro', models.AutoField(primary_key=True, serialize=False)),
                ('mimage', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('description', models.TextField()),
            ],
            options={
                'db_table': 'ordbitproduct',
            },
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('idu', models.BigAutoField(primary_key=True, serialize=False)),
                ('nompreu', models.CharField(max_length=100, null=True, verbose_name='Votre  Nom')),
                ('emailu', models.EmailField(max_length=254, null=True, unique=True, verbose_name=' Votre Email')),
                ('teleu', models.CharField(max_length=15, null=True, verbose_name='Votre Télephone')),
                ('mdpu', models.CharField(max_length=128, null=True, verbose_name='Votre  Mot de Passe')),
                ('entreprise', models.CharField(choices=[('ccbm', 'ccbm'), ('orbit', 'orbit')], max_length=30)),
                ('postu', models.CharField(max_length=128, null=True, verbose_name='Poste')),
                ('sectu', models.CharField(max_length=128, null=True, verbose_name='Secteur')),
                ('adresseu', models.CharField(max_length=15, null=True, verbose_name='Votre Adresse')),
                ('dateinsu', models.DateTimeField(default=datetime.datetime.now, null=True, verbose_name='date creation')),
                ('image', models.FileField(upload_to='photos', verbose_name='Profil')),
            ],
            options={
                'db_table': 'orbituser',
            },
        ),
        migrations.CreateModel(
            name='DétailsCommande',
            fields=[
                ('idet', models.AutoField(primary_key=True, serialize=False)),
                ('idpro', models.IntegerField()),
                ('quantite', models.IntegerField()),
                ('prix_unitaire', models.DecimalField(decimal_places=2, max_digits=10)),
                ('commande', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='home.commande')),
            ],
            options={
                'db_table': 'orbitdetailcom',
            },
        ),
    ]
