# Generated by Django 3.2.6 on 2023-08-04 12:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_changed_my_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('idnot', models.AutoField(primary_key=True, serialize=False)),
                ('etat', models.IntegerField(default=0)),
                ('date', models.DateTimeField(default=datetime.datetime.now)),
                ('typenot', models.CharField(default='direct', max_length=100)),
                ('message', models.TextField()),
            ],
            options={
                'db_table': 'ordbitnotification',
            },
        ),
    ]
