# Generated by Django 3.2.6 on 2023-08-04 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_changed_my_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='idclt',
            field=models.IntegerField(default='1'),
        ),
    ]
