# Generated by Django 3.2.6 on 2023-08-08 12:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_changed_my_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='dmdcredit',
            name='datedebut',
            field=models.DateTimeField(default=datetime.datetime.now, null=True, verbose_name='date creation'),
        ),
        migrations.AddField(
            model_name='dmdcredit',
            name='dateexpir',
            field=models.DateTimeField(null=True, verbose_name='date creation'),
        ),
        migrations.AddField(
            model_name='dmdcredit',
            name='debit',
            field=models.DecimalField(decimal_places=5, max_digits=100, null=True),
        ),
        migrations.AddField(
            model_name='dmdcredit',
            name='etatpayer',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='dmdcredit',
            name='montant',
            field=models.DecimalField(decimal_places=5, max_digits=100, null=True),
        ),
    ]
