# Generated by Django 3.2.6 on 2023-08-09 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_changed_my_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='dmdcredit',
            name='description',
            field=models.TextField(default='Hisen Frigo', null=True),
        ),
    ]
