# Generated by Django 3.2.6 on 2023-08-09 08:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_changed_my_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='dmdecheance',
            fields=[
                ('iddmdech', models.AutoField(primary_key=True, serialize=False)),
                ('iddmd', models.IntegerField()),
                ('date', models.DateTimeField(default=datetime.datetime.now)),
                ('etatpayer', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'orbitdmdecheance',
            },
        ),
    ]
