# Generated by Django 3.2.6 on 2023-08-09 08:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_changed_my_model'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dmdecheance',
            name='iddmd',
        ),
        migrations.AddField(
            model_name='dmdecheance',
            name='dmdcre',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='echeance', to='home.dmdcredit'),
            preserve_default=False,
        ),
    ]
