# Generated by Django 3.2.6 on 2023-08-09 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_changed_my_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='dmdecheance',
            name='idclt',
            field=models.IntegerField(default=1),
        ),
    ]
